# Generated by Django 4.0.2 on 2022-02-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_actor_movie_remove_actor_movie_actor_movies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(through='movies.Actor_Movie', to='movies.Movie'),
        ),
    ]
